version: "3.3"

services:
  stress-test-db:
    image: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5435:5432"
    deploy:
      resources:
        limits:
          memory: 1024M
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://test:test@stress-test-db:5432/test?schema=public
    deploy:
      resources:
        limits:
          memory: 1024M
    depends_on:
      - stress-test-db