version: "3.3"

services:
  postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 1024M
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
    env_file:
        - .env
    deploy:
      resources:
        limits:
          memory: 1024M
    depends_on:
      - postgres-db


#docker-compose --compatibility up -d